name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - '1.10'
          - '2.10'
          - '2.11'

    env:
      CMAKE_LDOC_FIND_REQUIRED: 'YES'

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: tarantool/setup-tarantool@v3
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Cache rocks
        uses: actions/cache@v3
        id: cache-rocks
        with:
          path: .rocks/
          key: cache-rocks-${{ matrix.tarantool }}-${{ hashFiles('membership-scm-1.rockspec') }}
      
      - name: Install dependencies
        if: steps.cache-rocks.outputs.cache-hit != 'true'
        run: |
          tarantoolctl rocks install luacheck
          tarantoolctl rocks install luatest
          tarantoolctl rocks install ldoc --server=https://tarantool.github.io/LDoc/

      - name: Add rocks to PATH
        run: echo ".rocks/bin" >> $GITHUB_PATH

      - name: Run luacheck
        run: luacheck membership-scm-1.rockspec membership.lua membership/

      - name: Build project
        run: tarantoolctl rocks make

      - name: Run tests
        run: .rocks/bin/luatest -v

      - name: Cleanup cached paths
        run: tarantoolctl rocks remove membership
