name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        tarantool: ['1.10', '2.6']
    runs-on: ${{ matrix.runs-on }}
    env:
      ROCKS_USERNAME: ${{ secrets.ROCKS_USERNAME }}
      ROCKS_PASSWORD: ${{ secrets.ROCKS_PASSWORD }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies (pytest)
        run: pip install -r test/requirements.txt
      - name: Install dependencies (tarantool)
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool }} bash
          sudo apt install -y tarantool tarantool-dev
          tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
          tarantoolctl rocks install luacheck
          echo ".rocks/bin" >> $GITHUB_PATH

      - name: Lint
        run: |
          luacheck membership-scm-1.rockspec
          flake8 test --ignore=E501

      - name: Build
        run: tarantoolctl rocks make BUILD_DOC=YES

      - name: Tests
        run: pytest -v

      - name: Release
        if: >
          matrix.runs-on == 'ubuntu-latest' &&
          matrix.tarantool == '1.10' &&
          (
            github.ref == 'refs/heads/master' ||
            startsWith(github.ref, 'refs/tags/')
          )
        run: |
          if [[ ${GITHUB_REF} =~ ^refs/tags/ ]]; then
            TAG=${GITHUB_REF##*/}
            ./release.sh $TAG
            ./upload.sh release/membership-${TAG}-1.rockspec
            ./upload.sh release/membership-${TAG}-1.all.rock
          else
            echo "Ref ${GITHUB_REF} is not a tag"
          fi

          ./upload.sh membership-scm-1.rockspec
